### PR TITLE
Add RCA Graph

### PR DESCRIPTION
**Pull request by k-jano**
This PR provide d3 graph in RCA dashboard. By default the first structure provided in ``/rca`` endpoint is generated in the dashboard. As in ``/graph`` dashboard, graph component covers whole possible area.

The demo with mocked data provided in separate [branch](https://github.com/openrca/orca-ui/tree/rca_graph_mock). Provided changes in this PR requires new endpoint in RCA backend.

### CODE REVIEW

**Review by bzurkowski — COMMENTED** [review]
@k-jano Overall LGTM. The graph-related code was nicely extracted. There is only one defect. The loaded graph viz. is too large:

Screenshot 2021-04-13 at 10 39 35

Can we set the scale to obtain the same results as in the main graph viz.?

**Comment by bzurkowski** [comment]
@k-jano I added mock for RCA API (#165 ). Please, rebase and test with the new payload. Thanks!

**Comment by k-jano** [comment]
@bzurkowski I adjust graph scale in ``/rca`` dashboard. WDYT?

rca_scale

We can easily manipulate graph scale by ``scale_const`` parameter. In my opinion presented graph should not also be too small, because it makes impression that the dashboard is incomplete. I also think, that after adding trajectory choice box dashboard graph will look better in new context.

**Review by bzurkowski — APPROVED** [review]
@k-jano Thanks, let's give it a try! 😉

**Pull request merged**
