### PR TITLE
RCA dashboard introduction

### PR DESCRIPTION
**Pull request by k-jano**
This is initial commit of RCA dashboard provided in OpenRCA UI.

Root Cause Analysis algorithm requires an initial object to perform analysis. The idea is to provide a comfortable way to enter the dashboard and start the calculation. The proper alert ``id`` will be passed to the subpage via query params. The way to construct link and redirect to subpage will be detailed implemented in following weeks.

So far the dashboard contains the most required logic to provide possibility to parallel programming. The PR contains routing, initializing a component state and performing an example of the request. Components like fault trajectory graph, rca output table etc will be provided in next PRs.

### CODE REVIEW

**Comment by bzurkowski** [comment]
```
http://localhost:8080/rca?source=XXX&time_point=YYY
```

**Comment by bzurkowski** [comment]
Let's assume the following initial RCA endpoint and fault trajectory payload:

```
/api/v1/rca?source=XXX&$time_point=YYY
```

```json
{
    "trajectories": [
        {
            "nodes": [],
            "links": [],
            "score": 0.555
        },
        {
            "nodes": [],
            "links": [],
            "score": 0.555
        },
        {
            "nodes": [],
            "links": [],
            "score": 0.555
        }
    ]
}
```

**Comment by k-jano** [comment]
@bzurkowski agree, I added ``time_point`` parameter handling and changed route to ``/rca``.

Let's provide handling a proper response in separate PR. This one is just introduction to make able work parallel at rca dashboard.

**Review by bzurkowski — APPROVED** [review]
@k-jano LGTM 👍

**Pull request merged**
