### PR TITLE
Add fault trajectory selector

### PR DESCRIPTION
**Pull request by k-jano**
This PR resolves PR by introducing basic fault trajectory selector. The main functionality is to choose one of provided fault trajectory, ordered by probability of occurrence. After selecting on of available item, the graph is reloaded with new trajectory. Thera are some still thigs todo, like styling selector box, or change general width and style of selector component. This features will be provided in separate PR.

Trajectories

### CODE REVIEW

**Comment by k-jano** [comment]
Closes #168

**Comment by k-jano** [comment]
I made some research connected with selector to satisfy UI requirements:
 - the most used library [react-select](https://react-select.com/home) doesn't support static selector option. It is based on dropdown indicator. I wasn't able to provide a satisfying view
 - I found another library [react-list-select](https://www.npmjs.com/package/react-list-select), less popular however provides a interesting view in form of list. We can try to stylize it to reach the view provided in #168.

Please look at a demo:
Trajectories2

Every list object is clickable, and after selecting the main graph is reloaded.

**Comment by k-jano** [comment]
@bzurkowski  After some stylization work we were able to obtain following view
selector_stylization

**Review by bzurkowski — CHANGES_REQUESTED** [review]
@k-jano Thanks for implementing the initial version of the fault trajectory selector!

Here are my comments regarding the styling:

* Add spacing between card border and the `Fault Trajectories` title. The spacing must be the same as in the node detail box.
* Change item padding to `20px`, i.e., `padding: 20px`.
* Set smaller font size, e.g., size equal to `Statistics`: `1rem`.
* Set item background to `#15181a` and remove the border.
* Set the smaller font size for trajectory scores, e.g., `0.75rem`.

**Comment by k-jano** [comment]
@bzurkowski After remarks the UI looks like:

FaulSelector

**Review by bzurkowski — APPROVED** [review]
Perfect! 👍

**Pull request merged**
